// Nodemailer email - will use Gmail SMTP once credentials arrive.
// For now logs to console so we can see what would be sent.

export async function sendEmail({ to, subject, html }) {
  // TODO: Once SMTP_USER and SMTP_PASS are provided, plug in nodemailer here.
  console.log(`\n[EMAIL] To: ${to}\n[EMAIL] Subject: ${subject}\n[EMAIL] (HTML omitted, ${html?.length || 0} chars)\n`);
  return { ok: true, mocked: true };
}

export function orderPlacedEmail(order) {
  const items = order.items.map(i => `<tr><td style="padding:8px;border-bottom:1px solid #f4d3e0">${i.name}${i.size ? ' · '+i.size : ''}${i.color ? ' · '+i.color : ''}</td><td style="padding:8px;border-bottom:1px solid #f4d3e0;text-align:center">${i.qty}</td><td style="padding:8px;border-bottom:1px solid #f4d3e0;text-align:right">₹${i.price * i.qty}</td></tr>`).join('');
  return `<!doctype html><html><body style="margin:0;background:#fdf2f7;font-family:'Segoe UI',sans-serif;color:#3d0a20;"><div style="max-width:640px;margin:0 auto;background:#fff;"><div style="background:linear-gradient(135deg,#C2185B,#E91E63);padding:40px 24px;text-align:center;color:#fff;"><h1 style="margin:0;font-family:Georgia,serif;font-size:32px;">Jeevikaa Couture</h1><p style="margin:8px 0 0;opacity:.9;letter-spacing:2px;font-size:12px;">LUXURY WOMEN'S FASHION</p></div><div style="padding:32px 24px;"><h2 style="font-family:Georgia,serif;margin:0 0 8px;">Thank you for your order! ✨</h2><p style="color:#7a5566;">Hi ${order.customer.fullName}, your order <strong>${order.orderId}</strong> has been placed successfully.</p><table style="width:100%;border-collapse:collapse;margin:24px 0;"><thead><tr style="background:#fce4ef;"><th style="padding:12px 8px;text-align:left;font-size:13px;">Item</th><th style="padding:12px 8px;font-size:13px;">Qty</th><th style="padding:12px 8px;text-align:right;font-size:13px;">Total</th></tr></thead><tbody>${items}</tbody></table><div style="padding:16px;background:#fdf2f7;border-radius:12px;"><div style="display:flex;justify-content:space-between;"><span>Subtotal</span><span>₹${order.subtotal}</span></div><div style="display:flex;justify-content:space-between;"><span>Shipping</span><span>${order.shipping ? '₹'+order.shipping : 'FREE'}</span></div><div style="display:flex;justify-content:space-between;font-weight:bold;color:#C2185B;font-size:18px;margin-top:8px;padding-top:8px;border-top:1px solid #f4d3e0;"><span>Grand Total</span><span>₹${order.total}</span></div></div><p style="margin-top:24px;color:#7a5566;">Payment method: <strong>${order.paymentMethod === 'cod' ? 'Cash on Delivery' : 'UPI / QR Payment'}</strong></p><p style="color:#7a5566;">Track your order anytime at <a style="color:#C2185B;" href="#">jeevikaacouture.com/track</a> using your Order ID.</p></div><div style="padding:20px;text-align:center;background:#3d0a20;color:#fce4ef;font-size:12px;">© Jeevikaa Couture · Handcrafted with love in India</div></div></body></html>`;
}
